import type { IntakeSectionDef } from "./types";

/**
 * First section of the intake. Probes whether the target is solving a
 * real, expensive, AI-shaped pain that customers are already paying
 * (or willing to pay) to resolve. Every answer captured here is an
 * unverified intake claim — downstream phases will reconcile these
 * against uploaded artifacts before letting them influence scoring.
 */
export const COMMERCIAL_PAIN_VALIDATION_SECTION: IntakeSectionDef = {
  section_key: "commercial_pain_validation",
  section_name: "Commercial Pain Validation",
  display_order: 1,
  description:
    "Establish that the target is selling into a real, expensive pain — not a feature looking for a buyer.",
  fields: [
    {
      key: "problem_statement",
      label: "What problem does the target claim to solve?",
      help: "One or two sentences in the company's own words. Save the analysis for later fields.",
      type: "long_text",
    },
    {
      key: "buyer_persona",
      label: "Who is the primary buyer / ICP?",
      type: "single",
      options: [
        "Mid-market operator (functional VP / Director)",
        "Enterprise buyer (line-of-business SVP / EVP)",
        "Technical buyer (CIO / CTO / Head of Eng)",
        "Compliance / Risk leader",
        "Finance / CFO office",
        "SMB owner / founder",
        "Public sector / regulated industry",
        "Other",
      ],
    },
    {
      key: "buyer_persona_notes",
      label: "Buyer persona — supporting detail",
      help: "Titles, sub-segments, or atypical buying-committee shape worth flagging.",
      type: "long_text",
    },
    {
      key: "pain_severity",
      label: "How severe is the pain for that buyer today?",
      help: "1 = nice-to-have. 5 = mission-critical / job-on-the-line.",
      type: "scale",
      scale_min: 1,
      scale_max: 5,
      scale_labels: ["Nice-to-have", "Mission-critical"],
    },
    {
      key: "pain_frequency",
      label: "How often does the pain hit the buyer?",
      type: "single",
      options: [
        "Continuously / daily",
        "Weekly",
        "Monthly",
        "Quarterly",
        "Annually",
        "Episodic / event-driven",
        "Unknown",
      ],
    },
    {
      key: "cost_of_pain_categories",
      label: "Which cost categories does the pain show up in?",
      help: "Select all that apply.",
      type: "multi",
      options: [
        "Lost revenue / pipeline",
        "Direct operating cost",
        "Compliance / regulatory penalty exposure",
        "Wasted headcount time",
        "Customer churn / NPS damage",
        "Reputational / brand risk",
        "Operational / safety risk",
        "Cost-of-capital / working-capital drag",
        "Other",
      ],
    },
    {
      key: "cost_of_pain_notes",
      label: "Quantified cost of the pain",
      help: "Dollar figures, hours, percentages — whatever the target has put on paper. Quote management directly where possible.",
      type: "long_text",
    },
    {
      key: "current_alternative",
      label: "What does the buyer use today to manage this pain?",
      type: "single",
      options: [
        "Manual workflow / human ops",
        "Internal tooling / homegrown software",
        "Spreadsheets / email",
        "Direct competitor product",
        "Adjacent / partial-fit vendor",
        "Outsourced service / BPO",
        "Nothing — pain is tolerated or ignored",
        "Unknown",
      ],
    },
    {
      key: "current_alternative_notes",
      label: "Current alternative — supporting detail",
      type: "long_text",
    },
    {
      key: "status_quo_failure",
      label: "Is the status quo measurably failing?",
      type: "single",
      options: [
        "Yes — quantified failure with documented impact",
        "Partially — anecdotes, no clean numbers",
        "Status quo works for most buyers today",
        "Unknown",
      ],
    },
    {
      key: "status_quo_failure_notes",
      label: "Status quo failure — supporting detail",
      help: "Specific metrics, incidents, or customer quotes that establish the failure mode.",
      type: "long_text",
    },
    {
      key: "customer_demand_evidence",
      label: "What evidence of customer demand exists today?",
      help: "Select every form of demand the target can produce.",
      type: "multi",
      options: [
        "Inbound demo / sales-qualified inbound",
        "Paid pilots in flight",
        "Signed LOIs / pre-orders",
        "Waitlist with named accounts",
        "Customer interviews / Jobs-to-be-Done research",
        "RFPs received naming this category",
        "Reference customers willing to renew at higher price",
        "Win/loss data showing buyers leaving incumbents",
        "None / not yet",
      ],
    },
    {
      key: "customer_demand_evidence_notes",
      label: "Customer demand — supporting detail",
      type: "long_text",
    },
    {
      key: "solution_fit",
      label: "How tightly does the target's solution fit the pain?",
      type: "single",
      options: [
        "Solves the full job-to-be-done end-to-end",
        "Solves the core step but leaves an adjacent gap",
        "Solves a workflow slice — buyer must stitch tools",
        "Adjacent solution — pain is partially addressed",
        "Unknown",
      ],
    },
    {
      key: "ai_necessity",
      label: "Is AI required to solve the pain, or a packaging choice?",
      type: "single",
      options: [
        "AI-only — no rules-based / deterministic path exists",
        "AI-preferred — meaningfully better quality than non-AI",
        "AI-optional — comparable to a non-AI build",
        "AI not required — pain is solvable without AI",
      ],
    },
    {
      key: "ai_necessity_notes",
      label: "AI necessity — supporting detail",
      help: "Why does AI move the needle here? What breaks if you swapped to a deterministic system?",
      type: "long_text",
    },
    {
      key: "promised_outcome",
      label: "What outcome does the target promise the buyer?",
      help: "Quote the marketing / sales claim verbatim where possible.",
      type: "long_text",
    },
    {
      key: "promised_outcome_notes",
      label: "Promised outcome — supporting detail",
      type: "long_text",
    },
    {
      key: "outcome_proof",
      label: "What proof exists that the outcome is delivered today?",
      type: "multi",
      options: [
        "Named customer case study with hard metrics",
        "Internal benchmark / before-after comparison",
        "Public eval suite results",
        "Independent third-party validation",
        "Reference call available on request",
        "Pilot results in writing",
        "None yet",
      ],
    },
    {
      key: "outcome_proof_notes",
      label: "Outcome proof — supporting detail",
      type: "long_text",
    },
    {
      key: "buying_trigger",
      label: "What triggers the buyer to actually purchase?",
      type: "multi",
      options: [
        "New regulation / compliance deadline",
        "Cost-cutting mandate",
        "Competitive threat / market share loss",
        "Org change — new exec sponsor",
        "Failed prior deployment of an alternative",
        "Tech refresh / platform migration",
        "Funding or M&A event",
        "Capacity / scale ceiling hit",
        "No clear trigger identified",
      ],
    },
    {
      key: "buying_trigger_notes",
      label: "Buying trigger — supporting detail",
      type: "long_text",
    },
    {
      key: "buying_urgency",
      label: "How urgent is the buying decision?",
      type: "single",
      options: [
        "Now — budget committed this quarter",
        "This fiscal year",
        "Next 12–18 months",
        "Beyond 18 months",
        "No defined timeline",
        "Unknown",
      ],
    },
    {
      key: "missing_pain_evidence",
      label: "What pain evidence is currently missing?",
      help: "Select every gap. These will be promoted into artifact requests in a later phase.",
      type: "multi",
      options: [
        "No quantified cost of the pain",
        "No customer interviews / JTBD on file",
        "No usage / telemetry data",
        "No win/loss analysis",
        "No referenceable paying customer",
        "No published case study",
        "No third-party validation",
        "No defined buying trigger",
        "Other",
      ],
    },
    {
      key: "missing_pain_evidence_notes",
      label: "Missing pain evidence — supporting detail",
      help: "What would unblock the gap? Note the artifact you would request from management.",
      type: "long_text",
    },
  ],
};
