-- Migration 00051: Add 'positioning' to mi_insights insight_type check constraint.
--
-- The positioning output (sub-segment rankings, entry strategies, stage
-- recommendation, adjacent/avoid categories) is generated by the same
-- LLM pipeline as the 7 insight types and benefits from the same
-- user_edited_content override pattern. Extending the CHECK constraint
-- to include 'positioning' is simpler than creating a separate table.

ALTER TABLE public.mi_insights
  DROP CONSTRAINT IF EXISTS mi_insights_insight_type_check;

ALTER TABLE public.mi_insights
  ADD CONSTRAINT mi_insights_insight_type_check
    CHECK (insight_type IN (
      'pressure_test',
      'structure_map',
      'threat_model',
      'company_shortlist',
      'gap_map',
      'adjacent_category',
      'timing_read',
      'positioning'
    ));
